import type { KeyboardDefinition, Project } from "./domain";
import {
  keyboardFromQmkMetadata,
  projectFromQmkKeymap,
  type QmkLayoutKey,
} from "./qmkMetadata";

const keychronV5MaxAnsiLayout = [
  { matrix: [0, 0], x: 0, y: 0 },
  { matrix: [0, 2], x: 2, y: 0 },
  { matrix: [0, 3], x: 3, y: 0 },
  { matrix: [0, 4], x: 4, y: 0 },
  { matrix: [0, 5], x: 5, y: 0 },
  { matrix: [0, 7], x: 6.5, y: 0 },
  { matrix: [0, 8], x: 7.5, y: 0 },
  { matrix: [0, 9], x: 8.5, y: 0 },
  { matrix: [0, 10], x: 9.5, y: 0 },
  { matrix: [0, 11], x: 11, y: 0 },
  { matrix: [0, 12], x: 12, y: 0 },
  { matrix: [0, 13], x: 13, y: 0 },
  { matrix: [0, 14], x: 14, y: 0 },
  { matrix: [0, 15], x: 15.25, y: 0 },
  { matrix: [0, 16], x: 16.25, y: 0 },
  { matrix: [0, 17], x: 17.25, y: 0 },
  { matrix: [0, 18], x: 18.5, y: 0 },
  { matrix: [1, 0], x: 0, y: 1.25 },
  { matrix: [1, 1], x: 1, y: 1.25 },
  { matrix: [1, 2], x: 2, y: 1.25 },
  { matrix: [1, 3], x: 3, y: 1.25 },
  { matrix: [1, 4], x: 4, y: 1.25 },
  { matrix: [1, 5], x: 5, y: 1.25 },
  { matrix: [1, 6], x: 6, y: 1.25 },
  { matrix: [1, 7], x: 7, y: 1.25 },
  { matrix: [1, 8], x: 8, y: 1.25 },
  { matrix: [1, 9], x: 9, y: 1.25 },
  { matrix: [1, 10], x: 10, y: 1.25 },
  { matrix: [1, 11], x: 11, y: 1.25 },
  { matrix: [1, 12], x: 12, y: 1.25 },
  { matrix: [1, 13], x: 13, y: 1.25, w: 2 },
  { matrix: [1, 15], x: 15.5, y: 1.25 },
  { matrix: [1, 16], x: 16.5, y: 1.25 },
  { matrix: [1, 17], x: 17.5, y: 1.25 },
  { matrix: [1, 18], x: 18.5, y: 1.25 },
  { matrix: [2, 0], x: 0, y: 2.25, w: 1.5 },
  { matrix: [2, 1], x: 1.5, y: 2.25 },
  { matrix: [2, 2], x: 2.5, y: 2.25 },
  { matrix: [2, 3], x: 3.5, y: 2.25 },
  { matrix: [2, 4], x: 4.5, y: 2.25 },
  { matrix: [2, 5], x: 5.5, y: 2.25 },
  { matrix: [2, 6], x: 6.5, y: 2.25 },
  { matrix: [2, 7], x: 7.5, y: 2.25 },
  { matrix: [2, 8], x: 8.5, y: 2.25 },
  { matrix: [2, 9], x: 9.5, y: 2.25 },
  { matrix: [2, 10], x: 10.5, y: 2.25 },
  { matrix: [2, 11], x: 11.5, y: 2.25 },
  { matrix: [2, 12], x: 12.5, y: 2.25 },
  { matrix: [2, 13], x: 13.5, y: 2.25, w: 1.5 },
  { matrix: [2, 15], x: 15.5, y: 2.25 },
  { matrix: [2, 16], x: 16.5, y: 2.25 },
  { matrix: [2, 17], x: 17.5, y: 2.25 },
  { matrix: [3, 18], x: 18.5, y: 2.25, h: 2 },
  { matrix: [3, 0], x: 0, y: 3.25, w: 1.75 },
  { matrix: [3, 1], x: 1.75, y: 3.25 },
  { matrix: [3, 2], x: 2.75, y: 3.25 },
  { matrix: [3, 3], x: 3.75, y: 3.25 },
  { matrix: [3, 4], x: 4.75, y: 3.25 },
  { matrix: [3, 5], x: 5.75, y: 3.25 },
  { matrix: [3, 6], x: 6.75, y: 3.25 },
  { matrix: [3, 7], x: 7.75, y: 3.25 },
  { matrix: [3, 8], x: 8.75, y: 3.25 },
  { matrix: [3, 9], x: 9.75, y: 3.25 },
  { matrix: [3, 10], x: 10.75, y: 3.25 },
  { matrix: [3, 11], x: 11.75, y: 3.25 },
  { matrix: [3, 12], x: 12.75, y: 3.25, w: 2.25 },
  { matrix: [3, 15], x: 15.5, y: 3.25 },
  { matrix: [3, 16], x: 16.5, y: 3.25 },
  { matrix: [3, 17], x: 17.5, y: 3.25 },
  { matrix: [4, 0], x: 0, y: 4.25, w: 2.25 },
  { matrix: [4, 2], x: 2.25, y: 4.25 },
  { matrix: [4, 3], x: 3.25, y: 4.25 },
  { matrix: [4, 4], x: 4.25, y: 4.25 },
  { matrix: [4, 5], x: 5.25, y: 4.25 },
  { matrix: [4, 6], x: 6.25, y: 4.25 },
  { matrix: [4, 7], x: 7.25, y: 4.25 },
  { matrix: [4, 8], x: 8.25, y: 4.25 },
  { matrix: [4, 9], x: 9.25, y: 4.25 },
  { matrix: [4, 10], x: 10.25, y: 4.25 },
  { matrix: [4, 11], x: 11.25, y: 4.25 },
  { matrix: [4, 12], x: 12.25, y: 4.25, w: 1.75 },
  { matrix: [4, 14], x: 14.25, y: 4.5 },
  { matrix: [4, 15], x: 15.5, y: 4.25 },
  { matrix: [4, 16], x: 16.5, y: 4.25 },
  { matrix: [4, 17], x: 17.5, y: 4.25 },
  { matrix: [4, 18], x: 18.5, y: 4.25, h: 2 },
  { matrix: [5, 0], x: 0, y: 5.25, w: 1.25 },
  { matrix: [5, 1], x: 1.25, y: 5.25, w: 1.25 },
  { matrix: [5, 2], x: 2.5, y: 5.25, w: 1.25 },
  { matrix: [5, 6], x: 3.75, y: 5.25, w: 6.25 },
  { matrix: [5, 10], x: 10, y: 5.25 },
  { matrix: [5, 11], x: 11, y: 5.25 },
  { matrix: [5, 12], x: 12, y: 5.25 },
  { matrix: [5, 13], x: 13.25, y: 5.5 },
  { matrix: [5, 14], x: 14.25, y: 5.5 },
  { matrix: [5, 15], x: 15.25, y: 5.5 },
  { matrix: [5, 16], x: 16.5, y: 5.25 },
  { matrix: [5, 17], x: 17.5, y: 5.25 },
] satisfies QmkLayoutKey[];

const macBase = [
  "KC_ESC", "KC_BRID", "KC_BRIU", "KC_MCTRL", "KC_LNPAD", "RGB_VAD", "RGB_VAI", "KC_MPRV", "KC_MPLY", "KC_MNXT", "KC_MUTE", "KC_VOLD", "KC_VOLU", "KC_DEL", "KC_HOME", "KC_END", "KC_MUTE",
  "KC_GRV", "KC_1", "KC_2", "KC_3", "KC_4", "KC_5", "KC_6", "KC_7", "KC_8", "KC_9", "KC_0", "KC_MINS", "KC_EQL", "KC_BSPC", "KC_NUM", "KC_PSLS", "KC_PAST", "KC_PMNS",
  "KC_TAB", "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P", "KC_LBRC", "KC_RBRC", "KC_BSLS", "KC_P7", "KC_P8", "KC_P9", "KC_PPLS",
  "KC_CAPS", "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_SCLN", "KC_QUOT", "KC_ENT", "KC_P4", "KC_P5", "KC_P6",
  "KC_LSFT", "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH", "KC_RSFT", "KC_UP", "KC_P1", "KC_P2", "KC_P3", "KC_PENT",
  "KC_LCTL", "KC_LOPTN", "KC_LCMMD", "KC_SPC", "KC_RCMMD", "MO(1)", "KC_RCTL", "KC_LEFT", "KC_DOWN", "KC_RGHT", "KC_P0", "KC_PDOT",
];

const macFn = [
  "KC_TRNS", "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8", "KC_F9", "KC_F10", "KC_F11", "KC_F12", "KC_TRNS", "KC_TRNS", "KC_TRNS", "RGB_TOG",
  "KC_TRNS", "BT_HST1", "BT_HST2", "BT_HST3", "P2P4G", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "RGB_TOG", "RGB_MOD", "RGB_VAI", "RGB_HUI", "RGB_SAI", "RGB_SPI", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "RGB_RMOD", "RGB_VAD", "RGB_HUD", "RGB_SAD", "RGB_SPD", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "BAT_LVL", "NK_TOGG", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
];

const winBase = [
  "KC_ESC", "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8", "KC_F9", "KC_F10", "KC_F11", "KC_F12", "KC_DEL", "KC_HOME", "KC_END", "KC_MUTE",
  "KC_GRV", "KC_1", "KC_2", "KC_3", "KC_4", "KC_5", "KC_6", "KC_7", "KC_8", "KC_9", "KC_0", "KC_MINS", "KC_EQL", "KC_BSPC", "KC_NUM", "KC_PSLS", "KC_PAST", "KC_PMNS",
  "KC_TAB", "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P", "KC_LBRC", "KC_RBRC", "KC_BSLS", "KC_P7", "KC_P8", "KC_P9", "KC_PPLS",
  "KC_CAPS", "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_SCLN", "KC_QUOT", "KC_ENT", "KC_P4", "KC_P5", "KC_P6",
  "KC_LSFT", "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH", "KC_RSFT", "KC_UP", "KC_P1", "KC_P2", "KC_P3", "KC_PENT",
  "KC_LCTL", "KC_LWIN", "KC_LALT", "KC_SPC", "KC_RALT", "MO(3)", "KC_RCTL", "KC_LEFT", "KC_DOWN", "KC_RGHT", "KC_P0", "KC_PDOT",
];

const winFn = [
  "KC_TRNS", "KC_BRID", "KC_BRIU", "KC_TASK", "KC_FILE", "RGB_VAD", "RGB_VAI", "KC_MPRV", "KC_MPLY", "KC_MNXT", "KC_MUTE", "KC_VOLD", "KC_VOLU", "KC_TRNS", "KC_TRNS", "KC_TRNS", "RGB_TOG",
  "KC_TRNS", "BT_HST1", "BT_HST2", "BT_HST3", "P2P4G", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "RGB_TOG", "RGB_MOD", "RGB_VAI", "RGB_HUI", "RGB_SAI", "RGB_SPI", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "RGB_RMOD", "RGB_VAD", "RGB_HUD", "RGB_SAD", "RGB_SPD", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "BAT_LVL", "NK_TOGG", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
  "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
];

export const keychronV5MaxKeyboard: KeyboardDefinition = keyboardFromQmkMetadata(
  {
    id: "keychron/v5_max/ansi_encoder",
    qmkKeyboard: "keychron/v5_max/ansi_encoder",
    displayName: "Keychron V5 Max ANSI Knob",
    manufacturer: "Keychron",
    aliases: ["V5 Max", "96%", "Keychron 96", "ANSI knob"],
    usb: {
      vid: "3434",
      pid: "0950",
    },
    source: {
      kind: "qmk",
      version: "keychron-qmk-b4bdf3f1-v5-max",
    },
    features: {
      backlight: {
        support: "unsupported",
        reason: "Lighting is exposed through RGB Matrix metadata.",
      },
      rgblight: {
        support: "unsupported",
        reason: "The QMK target enables RGB Matrix, not RGBLight.",
      },
      ledMatrix: {
        support: "unsupported",
        reason: "The QMK target enables RGB Matrix.",
      },
      rgbMatrix: {
        support: "supported",
        reason:
          "keyboards/keychron/v5_max/info.json enables rgb_matrix; ansi_encoder/config.h defines 97 LEDs.",
      },
      encoder: {
        support: "supported",
        count: 1,
        reason: "ansi_encoder/info.json enables encoder and encoder_map.",
      },
      via: {
        support: "supported",
        reason: "The target includes a VIA keymap and VIA JSON lighting menu.",
      },
      dynamicKeymap: {
        support: "supported",
        layers: 4,
        reason: "The VIA keymap exposes four layers.",
      },
      rawHid: {
        support: "supported",
        reason: "Parent info.json enables raw HID.",
      },
      macros: { support: "requiresBuild" },
      combos: { support: "requiresCustomC" },
      tapDance: { support: "requiresCustomC" },
    },
    layout: {
      id: "LAYOUT_ansi_98",
      qmkLayoutMacro: "LAYOUT_ansi_98",
      displayName: "ANSI 96% Knob",
      keys: keychronV5MaxAnsiLayout,
    },
    keyIdPrefix: "v5",
  },
  winBase,
);

export const keychronV5MaxProject: Project = projectFromQmkKeymap({
  id: "proj_keychron_v5_max",
  name: "Keychron V5 Max ANSI Knob",
  keyboard: keychronV5MaxKeyboard,
  layoutId: "LAYOUT_ansi_98",
  keymapName: "keychron_v5_max",
  catalogVersion: "keychron-qmk-b4bdf3f1-v5-max",
  lightingConditions: [
    {
      id: "fn_layer_glow",
      visualKeyId: "v5_091",
      name: "Fn hold",
      color: "#f2c94c",
      when: "Layer hold",
      layerIndex: 3,
      qmk: "MO(3)",
    },
    {
      id: "encoder_rgb_layer",
      visualKeyId: "v5_016",
      name: "Fn encoder",
      color: "#8cc8ff",
      when: "Fn layer",
      layerIndex: 3,
      qmk: "RGB_VAI",
    },
  ],
  layers: [
    { id: "layer_0", index: 0, name: "Mac Base", keycodes: macBase },
    { id: "layer_1", index: 1, name: "Mac Fn", keycodes: macFn },
    { id: "layer_2", index: 2, name: "Win Base", keycodes: winBase },
    { id: "layer_3", index: 3, name: "Win Fn", keycodes: winFn },
  ],
});
